# Generated by Django 3.2.18 on 2026-04-28 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headline', models.CharField(max_length=200)),
                ('subtext', models.TextField(blank=True)),
                ('background_image', models.ImageField(blank=True, null=True, upload_to='hero/')),
                ('cta_primary_label', models.CharField(blank=True, max_length=80)),
                ('cta_primary_url', models.CharField(blank=True, max_length=300)),
                ('cta_secondary_label', models.CharField(blank=True, max_length=80)),
                ('cta_secondary_url', models.CharField(blank=True, max_length=300)),
                ('is_active', models.BooleanField(default=True)),
                ('show_stats', models.BooleanField(default=True)),
                ('show_programs', models.BooleanField(default=True)),
                ('show_testimonials', models.BooleanField(default=True)),
                ('show_news', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Hero / Homepage',
                'verbose_name_plural': 'Hero / Homepage',
            },
        ),
        migrations.CreateModel(
            name='Stat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=120)),
                ('value', models.CharField(help_text='e.g. "1,200" or "98%"', max_length=40)),
                ('icon', models.CharField(blank=True, help_text='icon name or class', max_length=80)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('role', models.CharField(blank=True, help_text='e.g. Parent of Grade 8 Student', max_length=120)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='testimonials/')),
                ('quote', models.TextField()),
                ('rating', models.PositiveSmallIntegerField(default=5)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['order', '-id'],
            },
        ),
    ]
